SELECT A.ANIMAL_ID ANIMAL_ID, A.ANIMAL_TYPE ANIMAL_TYPE, A.NAME NAME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (A.SEX_UPON_INTAKE = 'Intact Female' 
       AND B.SEX_UPON_OUTCOME = 'Spayed Female')
       OR
       (A.SEX_UPON_INTAKE = 'Intact Male' 
       AND B.SEX_UPON_OUTCOME = 'Neutered male') ;
       

