SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) AS PRICE
              FROM FOOD_PRODUCT) ;


-- 다른 풀이
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1 ;

SELECT *
FROM (SELECT *
      FROM FOOD_PRODUCT
      ORDER BY PRICE DESC)
WHERE ROWNUM = 1 ;

-- WHERE 문에서 MAX(PRICE)로 풀 수 없는 문제
