SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC

-- CONCAT : 숫자를 문자로 바꿔주면서 문자열 결합시키기
-- ROUND : 1은 소수 첫째자리까지, 2는 소수 둘째자리까지 반올림