SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, B.MAX_COLONY - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A, (SELECT MAX(SIZE_OF_COLONY) AS MAX_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
                       FROM ECOLI_DATA
                       GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC ;


-- 굳이 JOIN을 할 필요 없이, FROM 에서 표 2개를 그냥 사용해도 됨