SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC


-- AVG : 평균 함수
-- DATEDIFF : 날짜 뺄셈 -> 뺄셈의 대상이 되는 두 날짜가 모두 일자에 포함이 되야 한다면 +1을 해줘야 함.